name: Check
on: [push]

jobs:
  standard-tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        task: [static-check]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Run ${{ matrix.task }}
        run: nix develop --command ${{ matrix.task }}