name: Check
on: [push]

jobs:
  standard-tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        task: [static-check]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: rainlanguage/rainix/.github/actions/nix-cachix-setup@main
        with:
          checkout: 'false'
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run ${{ matrix.task }}
        run: nix develop --command ${{ matrix.task }}
